# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci/ package.
os: linux
dist: xenial  # distro used by Travis, moveit_ci uses the docker image's distro
services:
  - docker
language: cpp
cache: ccache
compiler: gcc

notifications:
  email: true

env:
  global:
    - ROS_DISTRO=noetic
    - DOCKER_IMAGE=moveit/ros:noetic
    - UPSTREAM_WORKSPACE=https://github.com/rhaschke/python_qt_binding
    - CXXFLAGS="-Wall -Wextra -Wwrite-strings -Wunreachable-code -Wpointer-arith -Wredundant-decls -Wno-strict-aliasing"
    - WARNINGS_OK=false
    - ABI_BASE_URL=https://ni.www.techfak.uni-bielefeld.de/abicheck/rviz-${ROS_DISTRO}.tar.gz
    - BEFORE_SCRIPT="sed -i 's/if(ON)/if(1)/g' /usr/lib/x86_64-linux-gnu/cmake/assimp-5.0/assimpTargets.cmake"

  jobs:
    - TEST=catkin_lint,clang-format
    - TEST=abi,clang-tidy-fix

jobs:
  include:
    - compiler: clang
      env: BEFORE_SCRIPT="apt-get remove -q -y libogre-1.9.0v5; apt-get install -q -y libogre-1.12-dev; sed -i 's/if(ON)/if(1)/g' /usr/lib/x86_64-linux-gnu/cmake/assimp-5.0/assimpTargets.cmake"

before_script:
  - git clone -q --depth=1 https://github.com/rhaschke/moveit_ci.git .moveit_ci

script:
  - .moveit_ci/travis.sh
