Name:           ros-melodic-rviz
Version:        1.13.3
Release:        0%{?dist}
Summary:        ROS rviz package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/rviz
Source0:        %{name}-%{version}.tar.gz

Requires:       assimp-devel
Requires:       mesa-libGL-devel
Requires:       mesa-libGLU-devel
Requires:       ogre-devel
Requires:       qt5-qtbase
Requires:       qt5-qtbase-gui
Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-image-transport
Requires:       ros-melodic-interactive-markers
Requires:       ros-melodic-laser-geometry
Requires:       ros-melodic-map-msgs
Requires:       ros-melodic-media-export
Requires:       ros-melodic-message-filters
Requires:       ros-melodic-nav-msgs
Requires:       ros-melodic-pluginlib
Requires:       ros-melodic-python-qt-binding
Requires:       ros-melodic-resource-retriever
Requires:       ros-melodic-rosbag
Requires:       ros-melodic-rosconsole
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-roslib
Requires:       ros-melodic-rospy
Requires:       ros-melodic-sensor-msgs
Requires:       ros-melodic-std-msgs
Requires:       ros-melodic-std-srvs
Requires:       ros-melodic-tf
Requires:       ros-melodic-urdf
Requires:       ros-melodic-visualization-msgs
Requires:       tinyxml2-devel
Requires:       yaml-cpp-devel
BuildRequires:  assimp-devel
BuildRequires:  eigen3-devel
BuildRequires:  mesa-libGL-devel
BuildRequires:  mesa-libGLU-devel
BuildRequires:  ogre-devel
BuildRequires:  qt5-qtbase
BuildRequires:  qt5-qtbase-devel
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-cmake-modules
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-image-transport
BuildRequires:  ros-melodic-interactive-markers
BuildRequires:  ros-melodic-laser-geometry
BuildRequires:  ros-melodic-map-msgs
BuildRequires:  ros-melodic-message-filters
BuildRequires:  ros-melodic-nav-msgs
BuildRequires:  ros-melodic-pluginlib
BuildRequires:  ros-melodic-python-qt-binding
BuildRequires:  ros-melodic-resource-retriever
BuildRequires:  ros-melodic-rosbag
BuildRequires:  ros-melodic-rosconsole
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-roslib
BuildRequires:  ros-melodic-rospy
BuildRequires:  ros-melodic-rostest
BuildRequires:  ros-melodic-rosunit
BuildRequires:  ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-std-msgs
BuildRequires:  ros-melodic-std-srvs
BuildRequires:  ros-melodic-tf
BuildRequires:  ros-melodic-urdf
BuildRequires:  ros-melodic-visualization-msgs
BuildRequires:  tinyxml2-devel
BuildRequires:  urdfdom-devel
BuildRequires:  urdfdom-headers-devel
BuildRequires:  yaml-cpp-devel

%description
3D visualization tool for ROS.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Sat Mar 16 2019 William Woodall <william@osrfoundation.org> - 1.13.3-0
- Autogenerated by Bloom

* Sat Mar 09 2019 William Woodall <william@osrfoundation.org> - 1.13.2-0
- Autogenerated by Bloom

* Thu May 10 2018 D. Hood <dhood@osrfoundation.org> - 1.13.1-0
- Autogenerated by Bloom

* Fri Apr 27 2018 D. Hood <dhood@osrfoundation.org> - 1.13.0-0
- Autogenerated by Bloom

