Name:           ros-hydro-rviz
Version:        1.10.18
Release:        1%{?dist}
Summary:        ROS rviz package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/rviz
Source0:        %{name}-%{version}.tar.gz

Requires:       assimp
Requires:       eigen3-devel
Requires:       ogre-devel
Requires:       qt-devel
Requires:       ros-hydro-geometry-msgs
Requires:       ros-hydro-image-geometry
Requires:       ros-hydro-image-transport
Requires:       ros-hydro-interactive-markers
Requires:       ros-hydro-laser-geometry
Requires:       ros-hydro-map-msgs
Requires:       ros-hydro-media-export
Requires:       ros-hydro-message-filters
Requires:       ros-hydro-nav-msgs
Requires:       ros-hydro-pluginlib
Requires:       ros-hydro-python-qt-binding
Requires:       ros-hydro-resource-retriever
Requires:       ros-hydro-rosbag
Requires:       ros-hydro-rosconsole
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-roslib
Requires:       ros-hydro-rospy
Requires:       ros-hydro-sensor-msgs
Requires:       ros-hydro-std-msgs
Requires:       ros-hydro-std-srvs
Requires:       ros-hydro-tf
Requires:       ros-hydro-urdf
Requires:       ros-hydro-urdfdom
Requires:       ros-hydro-visualization-msgs
Requires:       tinyxml-devel
Requires:       yaml-cpp-devel
BuildRequires:  assimp-devel
BuildRequires:  eigen3-devel
BuildRequires:  ogre-devel
BuildRequires:  qt-devel
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-cmake-modules
BuildRequires:  ros-hydro-geometry-msgs
BuildRequires:  ros-hydro-image-geometry
BuildRequires:  ros-hydro-image-transport
BuildRequires:  ros-hydro-interactive-markers
BuildRequires:  ros-hydro-laser-geometry
BuildRequires:  ros-hydro-map-msgs
BuildRequires:  ros-hydro-message-filters
BuildRequires:  ros-hydro-nav-msgs
BuildRequires:  ros-hydro-pluginlib
BuildRequires:  ros-hydro-python-qt-binding
BuildRequires:  ros-hydro-resource-retriever
BuildRequires:  ros-hydro-rosbag
BuildRequires:  ros-hydro-rosconsole
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-roslib
BuildRequires:  ros-hydro-rospy
BuildRequires:  ros-hydro-sensor-msgs
BuildRequires:  ros-hydro-std-msgs
BuildRequires:  ros-hydro-std-srvs
BuildRequires:  ros-hydro-tf
BuildRequires:  ros-hydro-urdf
BuildRequires:  ros-hydro-urdfdom
BuildRequires:  ros-hydro-visualization-msgs
BuildRequires:  tinyxml-devel
BuildRequires:  yaml-cpp-devel

%description
3D visualization tool for ROS.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Tue Oct 07 2014 David Gossow <dgossow@gmail.com> - 1.10.18-1
- Autogenerated by Bloom

* Tue Jul 29 2014 David Gossow <dgossow@gmail.com> - 1.10.17-0
- Autogenerated by Bloom

* Tue Jul 29 2014 David Gossow <dgossow@gmail.com> - 1.10.18-0
- Autogenerated by Bloom

