Name:           ros-lunar-rviz
Version:        1.12.5
Release:        0%{?dist}
Summary:        ROS rviz package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/rviz
Source0:        %{name}-%{version}.tar.gz

Requires:       assimp
Requires:       eigen3-devel
Requires:       mesa-libGL-devel
Requires:       mesa-libGLU-devel
Requires:       ogre-devel
Requires:       qt5-qtbase
Requires:       qt5-qtbase-gui
Requires:       ros-lunar-geometry-msgs
Requires:       ros-lunar-image-transport
Requires:       ros-lunar-interactive-markers
Requires:       ros-lunar-laser-geometry
Requires:       ros-lunar-map-msgs
Requires:       ros-lunar-media-export
Requires:       ros-lunar-message-filters
Requires:       ros-lunar-nav-msgs
Requires:       ros-lunar-pluginlib
Requires:       ros-lunar-python-qt-binding
Requires:       ros-lunar-resource-retriever
Requires:       ros-lunar-rosbag
Requires:       ros-lunar-rosconsole
Requires:       ros-lunar-roscpp
Requires:       ros-lunar-roslib
Requires:       ros-lunar-rospy
Requires:       ros-lunar-sensor-msgs
Requires:       ros-lunar-std-msgs
Requires:       ros-lunar-std-srvs
Requires:       ros-lunar-tf
Requires:       ros-lunar-urdf
Requires:       ros-lunar-visualization-msgs
Requires:       tinyxml-devel
Requires:       urdfdom-headers-devel
Requires:       yaml-cpp-devel
BuildRequires:  assimp-devel
BuildRequires:  eigen3-devel
BuildRequires:  mesa-libGL-devel
BuildRequires:  mesa-libGLU-devel
BuildRequires:  ogre-devel
BuildRequires:  qt5-qtbase
BuildRequires:  qt5-qtbase-devel
BuildRequires:  ros-lunar-catkin
BuildRequires:  ros-lunar-cmake-modules
BuildRequires:  ros-lunar-geometry-msgs
BuildRequires:  ros-lunar-image-transport
BuildRequires:  ros-lunar-interactive-markers
BuildRequires:  ros-lunar-laser-geometry
BuildRequires:  ros-lunar-map-msgs
BuildRequires:  ros-lunar-message-filters
BuildRequires:  ros-lunar-nav-msgs
BuildRequires:  ros-lunar-pluginlib
BuildRequires:  ros-lunar-python-qt-binding
BuildRequires:  ros-lunar-resource-retriever
BuildRequires:  ros-lunar-rosbag
BuildRequires:  ros-lunar-rosconsole
BuildRequires:  ros-lunar-roscpp
BuildRequires:  ros-lunar-roslib
BuildRequires:  ros-lunar-rospy
BuildRequires:  ros-lunar-sensor-msgs
BuildRequires:  ros-lunar-std-msgs
BuildRequires:  ros-lunar-std-srvs
BuildRequires:  ros-lunar-tf
BuildRequires:  ros-lunar-urdf
BuildRequires:  ros-lunar-visualization-msgs
BuildRequires:  tinyxml-devel
BuildRequires:  urdfdom-headers-devel
BuildRequires:  yaml-cpp-devel

%description
3D visualization tool for ROS.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/lunar" \
        -DCMAKE_PREFIX_PATH="/opt/ros/lunar" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/lunar/setup.sh" ]; then . "/opt/ros/lunar/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/lunar

%changelog
* Mon May 01 2017 David Gossow <dgossow@gmail.com> - 1.12.5-0
- Autogenerated by Bloom

* Mon Apr 17 2017 David Gossow <dgossow@gmail.com> - 1.12.4-0
- Autogenerated by Bloom

